### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by LorenDorez** [davecoffin/nativescript-filterable-listpicker#11]
@davecoffin I know if the update you changed the view/styling a bit but not it looks funky on android see the below image

![image](https://user-images.githubusercontent.com/3706392/35400635-865be94e-01b4-11e8-84d0-bf18829cd7cd.png)

**Comment by davecoffin** [comment]
Hey Loren, sorry it took me so long to look into this. I cant reproduce it though. Changing the listWidth works fine for me. Can you include some code on how to reproduce this?

**Comment by LorenDorez** [comment]
I didnt do anything other than remove and install your plugin after you updated it and this is how it shows up.

**Comment by davecoffin** [comment]
Still, after the 2.0.0 update?

**Comment by LorenDorez** [comment]
No i havent updated yet. Working on another project today. Ill update later this week and let you know

**Comment by LorenDorez** [comment]
@davecoffin forgot to let you know that 2.0.0 fixed this issue
