### ISSUE TITLE
itemTapped event args.selectedItem is not working in listpicker

### ISSUE THREAD

**Issue by priyangamani** [davecoffin/nativescript-filterable-listpicker#12]
I tried to call api & bind the array of objects in listpicker.The listpicker dialog is working but i tried to keen the list item in itemtapped  event , the item is always undefined.

Js :
var arraytems=new ObservableArray([]);
for (var i = 0; i < res.length; i++) {
arraytems.push(res[i].list.toString());
}
Observable.set("listitems",arraytems);
Observable1.bindingContext = Observable;

public itemTapped(args) {
  #   alert(args.selectedItem + ' was tapped!')  //is always undefined...
}

<XML>
<ui:FilterableListpicker id="myfilter" blur="dark" hintText="Type to filter..." source="{{listitems}}" cancel="{{cancelFilterableList}}" itemTapped="{{itemTapped}}" />

![image](https://user-images.githubusercontent.com/6038069/35501096-d89fd3a2-0513-11e8-93e0-2d4f48d9cf70.png)

**Comment by davecoffin** [comment]
I see you closed this, mind commenting on what it was in case others come across this?
