### ISSUE TITLE
Feature Request: Ability to Reset Scroll

### ISSUE THREAD

**Issue by LorenDorez** [davecoffin/nativescript-filterable-listpicker#16]
I have a filterable listpicker and I update it several times with different list as the user fills out a form. But the issue i have ran into if i load List A and the user scrolls down to select an item. The later on i load List B the list is show at the last scroll position. I need the ability to reset the scroll position everytime i update the list of items

**Comment by leoncc** [comment]
This works:
```
@ViewChild("pickerListView") pickerListViewRef: ElementRef;
.....
_pickerListView: ListView;
.....
this._pickerListView = <ListView>this.pickerListViewRef.nativeElement;
this._pickerListView.items = newItems;
this._pickerListView.scrollToIndex(0);
```
