### ISSUE TITLE
Feature Request: rich text html description

### ISSUE THREAD

**Issue by alemartins414** [davecoffin/nativescript-filterable-listpicker#20]
Hi, I've been using this listpicker and so far it's been really helpful.
I got some demand on rich text html for it's description tho.
Is there a way to do it already? Is it on radar?

Thanks!

**Comment by davecoffin** [comment]
Can you be more specific, like maybe a mockup of what you're trying to achieve?

**Comment by alemartins414** [comment]
Can't make a mock up right now, but the idea is to make list items descriptions accept html tags.
If an item of my list is like "<b> It's a bold text </b>" the text appears bold in the list description.

**Comment by davecoffin** [comment]
Hey, I'm not going to add html support, but if there are specific styles you want support for you can let me know your specific case and I can see if it fits with the general goal of the plugin. Thats why I asked for a mockup. You can always edit the plugin code directly for your project if you need something more specific, but youre asking me to put work into an open source plugin without putting the time into showing me exactly what you want.

**Comment by delanick** [comment]
@davecoffin How would we go about editing the code itself? Is it under Node Modules? I'm an amateur so probably won't edit that code at all by myself, but for learning purposes I'd like to check it out :)

**Comment by davecoffin** [comment]
Yup, all plugins are in node_modules. You can edit the code right in the plugin, however remember if you ever remove and regenerate the platforms folder youll lose any changes. Another option is to fork the repo and reference a local copy in your package.json file, then you'll always be pointing at your forked code and you can do whatever you want.

**Comment by delanick** [comment]
@davecoffin Thanks so much, will keep that in mind :)

I also created an issue about styling the picker, would you mind having a look at that? :)

**Comment by davecoffin** [comment]
There are a ton of styling options now, take a look at all the options in the readme.

**Comment by delanick** [comment]
@davecoffin  again, see "legend" remark fom my other comment on my post :)

Thanks a ton!
