### ISSUE TITLE
Nativescript 4.0 Support

### ISSUE THREAD

**Issue by JijeshP** [davecoffin/nativescript-filterable-listpicker#22]
App Getting Crashed on android. Nativescript version 4.0

**Comment by delanick** [comment]
I also have this issue.

**Comment by shamoh19** [comment]
Yeah facing same issue. Even in IOS there are few errors in console though its working fine.

**Comment by davecoffin** [comment]
Share some code....

**Comment by delanick** [comment]
In my code behind, and it is also exported:

```
function showPicker(args) {
    var page = args.object;
    //page.getViewById('myfilter').show();
    console.log(JSON.stringify(page));
}
```

My XML (and I have included the namespace at the top):
```
<Button 
                            text="Choose City" 
                            tap="showPicker"
                            class="btn"
                            row="1" col="1" />
                    <ui:FilterableListpicker 
                        id="myfilter" 
                        blur="dark" 
                        hintText="Type to filter..." 
                        source="{{ cities }}" 
                        cancel="cancelFilterableList" 
                        itemTapped="itemTapped" />
                    <Label text="Vehicles:" />
```

**Comment by davecoffin** [comment]
Page is not args.object in that scenario. Typically youd set page in the loaded function, and your Page element would call the loaded function. args.object is whatever element initiated the function call. So args.object in your code is your Button. You would typically do something like

`<Page loaded="loaded">// all your UI </Page>`

then
```
var page;
export function loaded(args) {
  page = args.object;
}
```

**Comment by delanick** [comment]
So do I place my showPicker() in the loaded() function? How would I declare it, as a regular function like "function showPicker()" ?

**Comment by davecoffin** [comment]
If you are getting the Page object fine, follow the instructions here https://www.npmjs.com/package/nativescript-filterable-listpicker
`show` is a method on the FilterableListPicker object. `showFilter` is a function you define (can be called anything) that will get the object and call `show`. 

So youll have a button that calls showFilter, and in `showFilter` youll get the element in your view with `page.getViewById('myfilter')` or whatever ID you give it, and youll call show on that `page.getViewById('myfilter').show()`

**Comment by delanick** [comment]
I get all that, my confusion comes in at where in my code behind to place the showPicker() function as page was only declared in the loaded() function. How do I pass page context into showFilter() for it to be able to get the View? I'm sure you can see I'm an amateur :) Sorry to be wasting your time, I just really need this to work :)

**Comment by davecoffin** [comment]
declare page outside of the loaded function like in my comment above:

```
var page;
export function loaded(args) {
  page = args.object;
}
```

now page is everywhere.

**Comment by delanick** [comment]
Oh ok cool.

So page would then be able to get the View?  Thanks a ton bud!

**Comment by delanick** [comment]
Cool, so now it's at least not crashing, but the dialog isn't displaying. Nothing appears on screen.

**Comment by JijeshP** [comment]
@davecoffin  I think @delanick's issue is not related to 4.0 support right?

**Comment by delanick** [comment]
@JijeshP It must be now, as I just got it working, but it doesn't display as a dialog, it displays as a part of the page, pushing all the other elements down.

**Comment by JijeshP** [comment]
@delanick are you using nativescript 4.0.0 ?

**Comment by delanick** [comment]
I'm using Nativescript 4, not sure the exact version - how do I check?

**Comment by JijeshP** [comment]
@delanick tns info

**Comment by JijeshP** [comment]
@delanick Angular or core ? is it working on android ?

**Comment by delanick** [comment]
@JijeshP Don't laugh! I use Core. It works on Android, but not correctly, it doesn't display as a modal/dialog, it displays inline and moves all my other elements down, and looks terrible.

**Comment by JijeshP** [comment]
:) I use angular. not even opening in android and app crashes. Working fine on iOS

**Comment by delanick** [comment]
That sucks! But you say it works on iOS, that helps me at least as I haven't tested iOS yet.

**Comment by shamoh19** [comment]
@delanick can u share your code? For me even tap is not working and not getting error as well

**Comment by delanick** [comment]
@shamoh19 Are you using Core or Angular?

**Comment by davecoffin** [comment]
@delanick nothing wrong with using core. Angular is not for everybody. 

It displaying inline is a feature not a bug, you just need to adjust your layout. You can look at the included demo project here: https://github.com/davecoffin/nativescript-filterable-listpicker

This is basic {N} layout stuff: Everything in a `GridLayout` will stack on top of whatever comes before it. For example:

```
<GridLayout>
  <Image src="bgimg.png" /> // this is a background image, the label will display on top of it!
  <Label text="Hello world." />
</GridLayout>
```

So with that in mind, if you want the picker to display on top of your UI, you should place the `FilterableListPicker` element in a gridlayout on top of the rest of your UI. Then when you call show, it will show it in the manner you laid it out. Take a look at the demo project, thats why its there!

**Comment by JijeshP** [comment]
@davecoffin  4.0 Android issues only with Angular  ?

**Comment by JijeshP** [comment]
@davecoffin  WOW! 🥇  I tried few things but not working! :(

**Comment by delanick** [comment]
@davecoffin now that makes a ton of sense, thanks so much! I'm going to try that! Is there any way I can style it for Android, to make it look at bit more native? Currently it's styled very much towards iOS...

> It would make it way better if one of you would just figure it out and create a PR 🤪
hahahaha given the nature of my questions above, I'm going to politely decline and leave that to the real developers - see my "amateur" remark above :)

Good luck for the week from hell, I know the feeling!

**Comment by davecoffin** [comment]
@delanick The only difference between amateur and "real" developers is real developers pretend to know what theyre doing.

**Comment by delanick** [comment]
@davecoffin  that's funny! :)

Any advice on how to style it for Android :)

**Comment by davecoffin** [comment]
All the styling is done here: https://github.com/davecoffin/nativescript-filterable-listpicker/blob/master/src/filterable-listpicker.ts

Just jump into node modules and go nuts! To do it right, fork the repo, make local changes, and reference your local copy in package.json.

**Comment by delanick** [comment]
Thanks so much, gonna give it a try. Wish me luck, this amateur is about to break all your gard work :P I may contact you for further advice if you don't mind :)

**Comment by davecoffin** [comment]
Sure, plugin work can be confusing but its super fun.

**Comment by delanick** [comment]
@davecoffin Okay so I looked at it and it doesn't seem too difficult top style, yay! But I need one last piece of advice please, how will I separate it so that Android calls one style and iOS calls another - do I need to create two copies of the repo and then install both but link to either depending on the OS? Or is there a way I can style for both in the same doc?

> Sure, plugin work can be confusing but its super fun.

Agreed, looks super fun!! I just don't know TS very well, so this could get messy.

**Comment by davecoffin** [comment]
Notice this at the top:
`import { isIOS } from "tns-core-modules/platform";`
Thats a boolean indicating if its ios or not. So in the spot where we build the innerComponent html, do this:

```
let innerComponent;
if (isIOS) {
  innerComponent = builder.parse(`
    <GridLayout id="dc_flp_container" visibility="collapsed">
      // put all your iOS stuff here.
    </GridLayout>
  );
} else {
  innerComponent = builder.parse(`
    <GridLayout id="dc_flp_container" visibility="collapsed">
      // put all your android stuff here.
    </GridLayout>
  );
}

```

**Comment by davecoffin** [comment]
And TS is easy, learn it now. I consistently kick myself for doing my first {N} project in vanilla JS.

**Comment by delanick** [comment]
Thanks, will do that. Problem is, I don't have that file you sent. I just checked the plugin's files as they exist in my app currently and that file doesn't exist there - or am I being daft?

Will start TS as soo as this project is finished then :)

**Comment by davecoffin** [comment]
Where are you looking? You wont have a TS file if you try to edit the plugin directly. It will probably be
`node_modules/nativescript-filterable-listpicker/filterable-listpicker.js`. 
When you build a project, npm will download all the dependencies (plugins) and transpile ts into js. You'll run into the need to remove your node_modules folder during development, and when you do that, any changes you make in that folder will be blown away. Thats why you should fork the repo, make changes to the TS file, and put that dependency in your package.json file. So instead of 

`"nativescript-filterable-listpicker": "2.0.1"`
it would be
`"nativescript-filterable-listpicker": "file://../../whateverthepathistoyourfork/nativescript-filterable-listpicker"`

**Comment by delanick** [comment]
Ok cool, that makes some more sense. Thanks bud, will try it and revert! You've been awesome, much appreciated! :)

**Comment by davecoffin** [comment]
Ok, I just published 2.0.1 which adds support for {N} 4.0. I accept praise.

**Comment by shamoh19** [comment]
Thanks a lot for the effort  on your tight schedule

**Comment by delanick** [comment]
All hail @davecoffin !!

Could you tell me what you did to add that support, as part of my learning curve seeing as I'm now dabbling in messing around with plugins?

**Comment by delanick** [comment]
@davecoffin 

> @delanick nothing wrong with using core. Angular is not for everybody.

> It displaying inline is a feature not a bug, you just need to adjust your layout. You can look at the included demo project here: https://github.com/davecoffin/nativescript-filterable-listpicker

> This is basic {N} layout stuff: Everything in a GridLayout will stack on top of whatever comes before it. For example:
> 
> <GridLayout>
>   <Image src="bgimg.png" /> // this is a background image, the label will display on top of it!
>   <Label text="Hello world." />
> </GridLayout>
> So with that in mind, if you want the picker to display on top of your UI, you should place the FilterableListPicker element in a gridlayout on top of the rest of your UI. Then when you call show, it will show it in the manner you laid it out. Take a look at the demo project, thats why its there!

Worked like a charm bud, thanks so much!!
