### ISSUE TITLE
Disable the filterable text inpt

### ISSUE THREAD

**Issue by delanick** [davecoffin/nativescript-filterable-listpicker#23]
HI, it's people like you that make Nativescript so damn awesome to use, thank you so much for this, it's exactly what I was looking for!! :) I just came across it and will try it when I get back to work in a few hours.

Please advise, is there a way I can remove the filterable text input in some cases? I sometimes have small lists which don't need filtering, but would LOVE to also use this dialog as it's just so awesome!

Is there also a way I can style the dialog itself, like the background-color and border-radius etc?

Keep up the amazing work!

**Comment by delanick** [comment]
@davecoffin Please advise, could really do with your help here :)

**Comment by davecoffin** [comment]
Hey there, thanks for the kind words. Those arent available right now, and unfortunately I've got some bigger fish to fry at the moment. Feel free to fork the repo and mess around with the plugin, or just follow my instructions on how i created this and you can do whatever you want: https://www.nativescript.org/blog/filterable-list-picker-in-nativescript

**Comment by delanick** [comment]
@davecoffin Thanks, will try it out.

**Comment by davecoffin** [comment]
You can do this now by passing `enableSearch="false"` as an option.

**Comment by delanick** [comment]
@davecoffin You're awesome - saw the updates earlier today, thanks bud!! :)
