### ISSUE TITLE
Show Selected Item in Filter Select

### ISSUE THREAD

**Issue by leocrawf** [davecoffin/nativescript-filterable-listpicker#26]
Thank you for this awesome filter select. I have tried a few and this is the best so far. My only issue now is that I do not know how to show the item that was previously selected. I would like after an item was selected and the user taps to show the list again the previously selected item will be shown. It will not be a show stopper but a nice additive.

**Comment by davecoffin** [comment]
This is now possible in 2.2.2 using `selected` in your object, for example:
```
filterOptions = [
  {
    title: 'Uruguay',
    selected: '\uf121'
  },
  {
    title: 'Uganda'
  }
]
```

The list view item for Uruguay will display the icon '\uf121' towards the right, which is a check mark. You can use any icon youd like as long as you have some icon font in your project. It also appends a class `flp-item-selected`, so you dont have to use an icon you can make the previously selected item a different color or something.

**Comment by leocrawf** [comment]
Wow this is awesome. Thanks for the update.

**Comment by ExaltedJim** [comment]
Hi, can you please tell me how to dynamically change the selected item when a user changes it to another item in the list? I've tried to set the selected property in the itemTapped method but it doesn't seem to have an effect.

Thanks.

**Comment by davecoffin** [comment]
Just follow the instructions, the selected item comes back in args.selectedItem.
