### ISSUE TITLE
Default styles missing modal background color.

### ISSUE THREAD

**Issue by bearoutthere** [davecoffin/nativescript-filterable-listpicker#36]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both - Android
- iOS/Android versions - 27
- emulator or device. What type of device? - Emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) - 4.2.0
- Cross-platform modules: (check the 'version' attribute in the - 4.2.1
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project) - 4.2.0
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here) - 1.1.7

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

Unlike in the animated example the picker popup is missing the white box around the content.  Screenshot attached.
![screenshot from 2018-10-12 15-32-42](https://user-images.githubusercontent.com/1024870/46858398-723d2b00-ce35-11e8-80c7-e3e74c7371f9.png)

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by bearoutthere** [comment]
Also noticed the following error from the plugin's emplate in filterable-listpicker.js line 50.
Not sure why that image is being imported.

```
JS: Error in downloadBitmap - java.io.FileNotFoundException: https://davecoffin.com/images/expert_badge.png
```

**Comment by NathanWalker** [comment]
Have you tried adding background-color to the styles on the container in question?
https://github.com/davecoffin/nativescript-filterable-listpicker/blob/master/demo/app/app.css

**Comment by bearoutthere** [comment]
That was the problem.  I assumed that the plugin will also include the appropriate styles.  But adding the stiles from the above link solved the problem.  Thank you.
