### ISSUE TITLE
Caching image before show 

### ISSUE THREAD

**Issue by kefahB** [davecoffin/nativescript-filterable-listpicker#38]
Hi @davecoffin,

Thank you for your grate work.

Can we store `caching` the images before show on the UI ? because for à lot of contact list, the images will slowly appear; I recognized the plugin may use the `cache image widget` of Nativescript because the second time when we open the list picker all images appear at once.

Thanks

**Comment by stevenspiel** [comment]
I agree, caching would make a lot of sense

**Comment by kefahB** [comment]
I closed due to PR 🙂
