### ISSUE TITLE
Issue with running Demo app. 

### ISSUE THREAD

**Issue by GeorgeRXia** [davecoffin/nativescript-filterable-listpicker#39]
### Make sure to check the demo app(s) for sample usage 
Can you point me an nativescript angular example?
### Make sure to check the existing issues in this repository 
Checked
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

For Angular, I am having trouble running the plugin and getting access issue described below. This also occurs when I try to run the Demo App. 

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?
Android, I was using a Samsung Galaxy 6
### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) - 5.0.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) - "version": "4.2.1"
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)- 
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
{
  "nativescript": {
    "id": "org.nativescript.demo",
    "tns-ios": {
      "version": "4.0.1"
    },
    "tns-android": {
      "version": "4.0.1"
    }
  },
  "dependencies": {
    "nativescript-filterable-listpicker": "file:../src",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-unit-test-runner": "^0.3.4",
    "tns-core-modules": "^4.0.0"
  },
  "devDependencies": {
    "awesome-typescript-loader": "~3.1.3",
    "babel-traverse": "6.12.0",
    "babel-types": "6.11.1",
    "babylon": "6.8.4",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "filewalker": "0.1.2",
    "jasmine-core": "^2.5.2",
    "karma": "^1.3.0",
    "karma-jasmine": "^1.0.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "libs",
    "nativescript-dev-webpack": "^0.7.3",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "tns-platform-declarations": "^3.1.0",
    "tslint": "~5.4.3",
    "typescript": "~2.3.0",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
  "scripts": {
    "build.plugin": "cd ../src && npm run build",
    "ci.tslint": "npm i && tslint --config '../tslint.json' 'app/**/*.ts' --exclude '**/node_modules/**'",
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

When I run the demo app i get this error: 

Unable to apply changes on device: 04157df4e07b5b08. Error is: {
  "error": "unregistered users are not allowed to access package tns-android"
}

This also occurs when I try to also use an Angular App. I use the command tns debug android to run it.

**Comment by davecoffin** [comment]
That error has nothing to do with this plugin.

**Comment by davecoffin** [comment]
All the angular instructions are right in the Readme. Based on your error I would guess you skipped the part where it explains you must add this to your app.component:
```
import {registerElement} from "nativescript-angular/element-registry";
registerElement("FilterableListpicker", () => require("nativescript-filterable-listpicker").FilterableListpicker);
```

Follow the angular instructions and youll be fine.

**Comment by GeorgeRXia** [comment]
Thank you, I just solved it too. I didn't skip it but for some reason when i copied pasted it was 
registerElement("FilterableListpicker", () => require("nativescritns pt-filterable-listpicker").FilterableListpicker);

Going to close this. Thank you for taking the time
