### ISSUE TITLE
iOS positioning with keyboard

### ISSUE THREAD

**Issue by stevenspiel** [davecoffin/nativescript-filterable-listpicker#43]
### Which platform(s) does your issue occur on?
- Xcode emulator iPhone 6 iOS 12.0.1

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.0-2018-12-14-12741

### Please, tell us how to recreate the issue in as much detail as possible. 
Using the demo app, the iOS location of the modal is still centered when the keyboard is present, though I would expect it to be positioned at the top of the screen.

<img width="517" alt="screen shot 2018-12-29 at 11 43 00 am" src="https://user-images.githubusercontent.com/1630091/50540423-8b659600-0b5f-11e9-9518-82f806b2b940.png">

It makes sense for it to be vertically centered when the keyboard is hidden, but the Android modal goes to the top of the screen as expected.

<img width="498" alt="screen shot 2018-12-29 at 11 49 27 am" src="https://user-images.githubusercontent.com/1630091/50540438-d2538b80-0b5f-11e9-9d2d-d62915d19e55.png">

**Comment by stevenspiel** [comment]
I was able to solve it by adjusting the size of its container when the keyboard appears, though there must be a more elegant solution.

**Comment by davecoffin** [comment]
Yea this interaction just relies on the native approach, Android adjusts the viewport when keyboard is shown, iOS does not. There are many ways to skin this cat so I'm going to leave it up to the developer to solve it like you did.
