### ISSUE TITLE
unable to apply styling in nativescript angular project

### ISSUE THREAD

**Issue by tahir-jamil** [davecoffin/nativescript-filterable-listpicker#45]
hear is the code 

what i am missing ?
  ```
<FilterableListpicker  [rowSpan]="rowSpan" #myfilter blur="dark" enableSearch="true" [hintText]="hintText" [source]="source" (canceled)="cancelFilterableList($event)"
(itemTapped)="itemTapped($event)"></FilterableListpicker>
```

> styling

    .flp-container .flp-list-container {
        border-radius: 10;
      }
      .flp-container .flp-list-container .flp-listview {
        background-color: white;
      }
      
      .flp-container .flp-list-container .flp-listview .flp-row {
        background-color: white;
      }
      /* .flp-container .flp-list-container .flp-listview .flp-row .flp-row-container {
        padding: 10;
      } */
      .flp-container .flp-list-container .flp-listview .flp-row .flp-image {
        margin: 10 0 10 5;
      }
      .flp-container .flp-list-container .flp-listview .flp-row .flp-title-container {
        margin: 10 10 10 5;
        /* margin: 0 10 0 10; */
      }
      .flp-container .flp-list-container .flp-listview .flp-row .flp-title-container .flp-title {
        font-weight: bold; 
        font-size: 16;
      }
      .flp-container .flp-list-container .flp-listview .flp-row .flp-title-container .flp-description {
        color: gray; 
        font-size: 13;
      }
      .flp-container .flp-list-container .flp-listview .flp-row .flp-title-container .flp-no-title {
        margin-left: 15; 
        padding: 10 0;
      }
      .flp-container .flp-list-container .flp-listview .flp-row .flp-item-selected {
        color: lightblue;
      }
      
      .flp-container .flp-hint-field {
        padding: 10 15; 
        height: 40; 
        background-color: #E0E0E0; 
        border-radius: 10 10 0 0;
      }
      
      .flp-container .flp-cancel-container {
        background-color: #E0E0E0; 
        height: 40; 
        border-radius: 0 0 10 10;
      }
      
      .flp-container .flp-cancel-container .flp-btn-cancel {
        font-weight: bold; 
        height: 40; 
        background-color: transparent; 
        border-color: transparent; 
        border-width: 1; 
        font-size: 12;
      }

**Comment by davecoffin** [comment]
You have to call the show method.

Dave Coffin
davecoffin.com

**Comment by tahir-jamil** [comment]
model is shown but i want to style this

**Comment by ExaltedJim** [comment]
Having the same problem too since upgrading from 2.1.0 to 2.2.4 in my angular project. After upgrading, the style of the list picker looks all wrong, and I can't seem to change it by modifying the documented css classes. Here is what my list picker looks like after upgrading to 2.2.4:

![Screen Shot 2019-03-25 at 4 51 27 pm](https://user-images.githubusercontent.com/3637359/54906508-57abc980-4f1e-11e9-866f-992123b03d87.png)

Here is what it used to look like in 2.1.0:

![Screen Shot 2019-03-25 at 5 21 36 pm](https://user-images.githubusercontent.com/3637359/54908271-790eb480-4f22-11e9-81d7-161331637f21.png)

Any advice would be appreciated.

**Comment by davecoffin** [comment]
Just drop the css in the readme into app.css or your sass file. I just tested this approach and it works fine in an angular project.
