### ISSUE TITLE
Error after upgrading to the latest nativescript cli

### ISSUE THREAD

**Issue by jannomeister** [davecoffin/nativescript-filterable-listpicker#48]
When I call `this.myFilter.nativeElement.show()` I got this error from the console -> **'container.visibility = 'visible'**

**Comment by jannomeister** [comment]
btw, I'm using Nativescript-Angular.

**Comment by davecoffin** [comment]
Just published an update thanks to @NathanWalker that should address this. Let me know if it fixes it for you.
