### ISSUE TITLE
Feature Request: Bind to Objects

### ISSUE THREAD

**Issue by LorenDorez** [davecoffin/nativescript-filterable-listpicker#5]
It would be nice to be able to bind this list to an array of objects and pass in the displayText property.

Example

```
listItems = [
     {Id: 1, Name: "Item 1"},
     {Id: 2, Name: "Item 3"},
     {Id: 3, Name: "Item 3"},
]
```

**Comment by davecoffin** [comment]
Good idea, I may work this into an effort to also include an image for the list view items.

**Comment by arcovoltaico** [comment]
Really nice plugin, I can't wait for this feature for using everywhere ;-)

**Comment by arcovoltaico** [comment]
I don’t if it’s posible keeping good performance, but would love to be able you use more than two attributes for elements in the array and can use css in order to create nice looking pickers including name, description and a photo

**Comment by davecoffin** [comment]
What do you mean by `use more than two attributes for elements`?

**Comment by arcovoltaico** [comment]
That the array can be something like [{‘id’: 1, ‘name’: ‘abc’, ‘image’: ‘url1’, ...}, {...}]

**Comment by davecoffin** [comment]
It would need to be a defined structure, so unlikely you could supply an object thats the result of a REST API call. However, its trivial to create an array of strings (what is currently supported), or an array of objects with predefined keys for the listpicker to display, and access the results of the tap event by using the index. For example:

- You get a response from an API call with an array of objects, specific to that API.
- Right now since it only supports an array of strings, you do something like
```
let responseArray; // heres the array of objects from your api
let filterableArray: Array<any> = [];
responseArray.forEach(item => {
    filterableArray.push(item.name);
})
bindingContext.filterableArray = filterableArray;
```

and then on the tap, grab the index tapped and just do

```
let selectedObject = responseArray[args.index];
```

And once I add support for more object keys, create the objects in the `forEach` and put them in your filterableArray. As long as you keep that array in sync with subsequent calls to the api or user interactions, the index will always match.

**Comment by arcovoltaico** [comment]
It's a nice solution for sync with the API, but I'd prefer a defined structure (id, name, image, description and price) or better a support for any structure and can assign a templateUrl and css where override the layout .

**Comment by LorenDorez** [comment]
@davecoffin thats a nice workaround for now but requires me having 2 objects for each dropdown. I would like to avoid that if possible.

**Comment by davecoffin** [comment]
Its not really a workaround, the plugin needs a simple array of strings to know what to display for options. If you provide an arbitrary object, how would it know what key is for label display? My plan to support this feature is to accept an object of type `FilterableListItem` for example being something like:

```
{
  name: String
  description: String // display this under main label
  image: ImageAsset // display this to the left of name and description
  icon: ImageAsset // display this to the right of the cell
}
```

**Comment by LorenDorez** [comment]
Couldnt web provide what to display via a property like DisplayText="name" and that would tell you to look at the name property?

Also you idea for a FilterableListItem works i have some suggections though. 
1. Include an ID even if its not used in display would be useful for people with APIs.
2. Allow for like a data Attribute that we can plugin other info/properties we might need on the item tap but arent used fo display purposes

**Comment by davecoffin** [comment]
I would think as long as the object you provide has keys that match what the plugin will use, you can pass anything you like. for example, pass an object like this:
```
{
  "name": "Its a beautiful day in the neighborhood",
  "id": "22",
  "description": "The land of make believe.",
  "data": {
    "entity": "Daniel Tiger"
  }
}
```
and the plugin would display `name` and `description`.

**Comment by davecoffin** [comment]
but again, this is all possible now with simple strings, you can map your display array to your data array by just using the index.

**Comment by LorenDorez** [comment]
Yes bu the issue for me is not i have to keep 2 references one with all data and one with just string for the display. On a form that has 10-15 dropdown/lists thats a lot IMO

**Comment by LorenDorez** [comment]
Also i just tried this but get an error saying index is undefined

**Comment by LorenDorez** [comment]
It appears you do no forward index through the notify function

**Comment by LorenDorez** [comment]
i added index to the args that are passed to the itemTapped event but if you use the filtering the index is no longer valid as its the index of the filtered datasource and not the original . This is why we need to be able to bind to objects not just flat string arrays

**Comment by davecoffin** [comment]
Hey,
Sorry I havent had time to work on this this week. I'll get to it I promise! In the meantime though, all this is pretty easily accomplished in nativescript without the plugin, you can read all about how i did it here: https://www.nativescript.org/blog/filterable-list-picker-in-nativescript

What I'd recommend for now though is create a map of your API results. Something like this:

```
public itemsToShow = []; //this is for the filterable list picker.
private itemsMap = {};
apiResults.forEach(item => {
    itemsToShow.push(item.title);
    itemsMap[item.title] = item;
})
```

then in your function that accepts the selected index:
```
let selectedObject = this.itemsMap[this.itemsToShow[args.index]];
```

In english, store a map of your API response objects with the string you use in the list picker as the key, then just get the object in the map when selects the string. Super simple.

**Comment by LorenDorez** [comment]
I just do this for now. I just dont have the free time to try an learn how to do a pull request. I have been reading up on Nativescript etc.. and reviewing the core plugins and i know how and what to change to make this plugin bind against an object array just have to find time to do a PR

```
viewModel.page.getViewById("AddressDisplay").text = args.selectedItem;
                    viewModel.dataSources.address.forEach((address) => {
                        if (address.StreetAddress1 === args.selectedItem) {
                            viewModel.citation.AddressId = address.AddressId;
                        }
                    });
```

**Comment by davecoffin** [comment]
That works too, my approach above will be a little more performant as you dont need to loop through an array every time then user taps an option.

**Comment by davecoffin** [comment]
I'm still planning on doing this, maybe tomorrow.

**Comment by davecoffin** [comment]
This is done! Sorry it took so long. Take a look at the readme for instructions and the gif for what it will look like.

**Comment by LorenDorez** [comment]
@davecoffin 
Awesome looks good. Does the SelectedItem return the Original item from the array include all its additional properties?

**Comment by davecoffin** [comment]
Yes, it does. Give it a try!
