### ISSUE TITLE
Publish the last PR Please :-)

### ISSUE THREAD

**Issue by kefahB** [davecoffin/nativescript-filterable-listpicker#56]
Hi @davecoffin @shiv19 ,

Please can you publish the last PR to `npm`, because the is an issue with the `Typescript`

Webpack block the CLI with those errors
```ts
ERROR in node_modules/nativescript-filterable-listpicker/index.d.ts(30,9):
TS1086: An accessor cannot be declared in an ambient context.

ERROR in node_modules/nativescript-filterable-listpicker/index.d.ts(31,9):
```

**Comment by shiv19** [comment]
@kefahB only Dave can publish it as of now 😅

**Comment by davecoffin** [comment]
@shiv19 did we resolve the demo not building on ios?
