### ISSUE TITLE
listHeight not working as expected

### ISSUE THREAD

**Issue by arcovoltaico** [davecoffin/nativescript-filterable-listpicker#7]
When I am increasing the listHeight to 400, only the wrapper is resized. leaving a blank space below the Cancel button.

       <FilterableListpicker #myfilter blur="dark" hintText="Type to filter..." 
        listHeight="400" [source]="elements" (canceled)="cancelFilterableList($event)"
            (itemTapped)="itemTapped($event)"></FilterableListpicker>

This is happening on iPhone SE iOS11 Simulator.
Btw, it would be great if listHeight could be set to 100% or auto.
Thanks.

**Comment by davecoffin** [comment]
This is fixed with 1.0.5
